module.exports = [
    {
      name: "Mario Kart 8 Deluxe",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPAABPA",
      publisher: "Nintendo",
      sku: "1",
      product_sku: "5723304",
      release_date: "04/28/2017",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-7.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Battle new enemies on a host of fun tracks with Mario Kart 8 Deluxe for the Nintendo Switch. Three new vehicles and a smart steering feature make this game perfect for both beginners or seasoned pros. In Mario Kart 8 Deluxe you can hold up to two items at a time to attack your enemies.",
      features: "Race your friends in the definitive version of Mario Kart 8, only on Nintendo Switch!\n Race as every character on every track from the Wii U version, including DLC characters and tracks \n Pop some balloons in the revamped Battle mode, complete with Balloon Battle and Bob-omb Blast \n Battle on new courses, like Urchin Underpass and Battle Stadium, or returning ones, such as GCN Luigi\"s Mansion and SNES Battle Course 1 \n Inkling Girl & Inkling Boy from Splatoon, King Boo, Dry Bones, and Bowser Jr. join the roster! \n Choose a new Smart Steering feature which makes driving and staying on the track easy even at 200cc \n Three new vehicles have been added, two are even inspired by Splatoon \n Carry two items at the same time \n Returning items include Boo, the item stealing ghost, and the Feather, which gives you a high jump in battle mode \n Drive through in 1080p HD quality in TV mode \n For 1 player or up to 12 players online multiplayer* \n * Nintendo Switch Online membership (sold separately) and Nintendo Account required for online play. Not available in all countries. Internet access required for online features. Terms apply. nintendo.com/switch-online",
      included: "Mario Kart 8 Deluxe",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/20e8f7ed4abe4ce59da5126768578888.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1799536929_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1044944662_ap.jpg;maxHeight=112;maxWidth=200"],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1858858501&amp;mobile=true",
      video_length: ["5:02"],
      reviews_count: 34,
      reviews_breakdown: [8,7,7,10,2],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "Comic mischief", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Recommended Minium Age", "Model Number"],
      general: ["Mario Kart 8 Deluxe", "Nintendo", "Nintendo", "Nintendo", "0 years", "HACPAABPA"],
      game_Details_title: ["Genre", "Game Franchise", "Game Series", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Racing", "Mario Kart", "8", "Yes", "12", "No"],
      requirements_title: ["System Requirements", "Subscription", "Download Requirements"],
      requirements: ["Nintendo Switch, Nintendo Switch Online membership, Nintendo Account", "No", "Nintendo Account"],
      other_title: ["UPC"],
      other: "045496590475",
      questions: 27,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/general/cyp.placeholder_mariokart.png",
      bundle_total : [69.99, 19.99, 59.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/manu_mario+kart+8+deluxe.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/general/questions_placeholder.png"
    },
    { 
      name: "Pokémon Sword Edition",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPALZAA",
      publisher: "Nintendo",
      sku: "2",
      product_sku: "6255366",
      release_date: "11/15/2019",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_7.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_8.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_9.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_10.png"],
      compatible_platforms : ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      geek_squad_price: 7.99,
      description: "A new generation of Pokémon is coming to the Nintendo Switch system. Become a Pokémon Trainer, and embark on a journey in the new Galar region. Choose from one of three new partner Pokémon: Grookey, Scorbunny, or Sobble. In this all-new adventure, you'll encounter new and familiar Pokémon as you catch, battle, and trade Pokémon while exploring new areas. Get ready for the next Pokémon adventure in the Pokémon Sword and Pokémon Shield games.",
      features : "Unlike others found in the Galar region, this Meowth can Gigantamax to take on an imposing, elongated appearance capable of using a mighty G-Max Move! \n As you trek across this diverse region, you'll encounter wild Pokémon to catch and rival Trainers eager to battle. Choose one of three new partner Pokémon, strategically form a Pokémon team, bond with them throughout your journey, and face the odds together. \n Explore a whole new region full of never-before-seen Pokémon. \n Embark on a new Pokémon journey as a Pokémon Trainer. Catch, battle, and trade Pokémon on an all-new adventure in the Galar region",
      included: "Pokémon Sword Edition",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/d921a1a964bc841698d01cde4f15f720.jpg;maxHeight=112;maxWidth=200"],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1643758036&amp;mobile=true" ,
      video_length: ["2:13"],
      reviews_count: "28" ,
      reviews_breakdown: [3,6,4,9,6], 
      keyspecs_title: ["Edition", "ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["Sword Edition", "E (Everyone)", "Comic mischief, Mild cartoon violence", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Model Number"],
      general: ["Pokémon Sword Edition", "Nintendo", "Nintendo", "HACPAABPA"],
      game_Details_title: ["Edition", "Genre", "Game Franchise", "Game Series"],
      game_details: ["Sword Edition", "Role Playing", "Pokemon", "Sword and Shield"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements:["Nintendo Switch", "No"],
      other_title: ["UPC"],
      other: "045496590475",
      questions: 9,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/bundle_pokemon_sword_edition.png",
      bundle_total : [29.99, 19.99, 49.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/manu_pokemon_sword_edition.png",
      questions_img:"https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/questions_pokemon_sword_edition.png"
    },
    {
      name: "Super Smash Bros. Ultimate",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPAAABA",
      publisher: "Nintendo",
      sku: "3",
      product_sku: "5723319",
      release_date: "12/07/2018",
      esrb_rating: "E10+ (Everyone 10+)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_7.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Choose your character in Super Smash Bros. for Nintendo Switch. Its expanded roster and new levels let you brawl it out with your friends with your favorite characters in iconic locations from Nintendo games. Super Smash Bros. has both local and online multiplayer, so you can play with your friends wherever you go.",
      features: "New fighters, new stages, and every fighter ever featured in the series",
      included: "Super Smash Bros. Ultimate",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1297102016_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1514902275_ap.jpg;maxHeight=112;maxWidth=200" ],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1297102016&amp;mobile=true",
      video_length: ["0:57"],
      reviews_count: 20,
      reviews_breakdown: [2,4,5,4,5],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E10+ (Everyone 10+)", "Cartoon violence, Comic mischief, Mild suggestive themes", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher","Recommended Minium Age", "Model Number"],
      general: ["Super Smash Bros. Ultimate", "Nintendo", "10 years", "HACPAABPA"],
      game_Details_title: ["Genre", "Game Franchise", "Game Series", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Fighting", "Super Smash Bros.", "Ultimate", "Yes", "8", "No"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["Nintendo Switch", "No"],
      other_title: ["UPC"],
      other: "045496592998",
      questions: 54,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/bundle_super_smash-bros.png",
      bundle_total : [29.99, 24.99, 49.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/manu_super_smash_bros.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/questions_super_smash-bros.png"
    },
    {
      name: "Overcooked! 2",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "SOS01183",
      publisher: "Team17",
      sku: "4",
      product_sku: "6261023",
      release_date: "08/07/2018",
      esrb_rating: "E (Everyone)",
      price: 39.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-1.png","https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-7.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-8.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-9.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/overcooked2-10.png" ],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 5.99,
      description: "The Onion Kingdom is in peril again and this time it is the fault of the Onion King himself! Reading aloud from the fabled Necronomnomicon, he has cooked up a real problem in the form of a doughy but dangerous army of UNDEAD BREAD called…The Unbread! The Onion King needs you, so chop, fry and bake your way through an all new series of crazy kitchens to defeat them and save the kingdom.Overcooked 2 is a chaotic co-op cooking game for one to four players in which you must serve a variety of recipes including sushi, pasta, cakes, burgers and burritos to hungry customers in a series of unconventional kitchens. Work solo or with up to three friends to prep orders while overcoming obstacles such as fire, collapsing floors, overbearing waiters and of course, the classic kitchen problem of floating work surfaces.",
      features: "For the first time you can cook up a storm with up to four players in both local and online multiplayer ${<br>} Throwing is now an official game mechanic, allowing you to toss ingredients to your fellow chefs or even straight into the pan/blender/onto the floor. ${<br>}",
      included: "Overcooked! 2",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: [],
      miniplayer_videos: "",
      video_length: [],
      reviews_count: 31,
      reviews_breakdown: [6,5,8,5,7],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "No descriptors", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Model Number", "Color"],
      general: ["Overcooked! 2", "Team17", "Team17","SOS01183s", "Multi"],
      game_Details_title: ["Genre", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Social", "Yes", "4", "No"],
      requirements_title: ["Compatible Platform(s)", "Software Format"],
      requirements: ["Nintendo Switch", "Physical"],
      other_title: ["UPC"],
      other: "812303011832",
      questions: 1,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/bundle_overcooked2.png",
      bundle_total : [59.99, 54.99, 39.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/no_manu_overcooked2.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Overcooked-2/questions_overcooked2.png"
    },
    {
      name: "New Super Mario Bros. U Deluxe",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPADALA",
      publisher: "Nintendo",
      sku: "5",
      product_sku: "6311892",
      release_date: "01/01/2019",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-4.png","https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-7.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/deluxe-8.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Join Mario, Luigi, and pals for single-player or multiplayer fun anytime, anywhere. Take on two family-friendly, side-scrolling adventures with up to three friends* as you try to save the Mushroom Kingdom. Includes the New Super Mario Bros. U game and a harder, faster New Super Luigi U game - both of which include Nabbit and Toadette as playable characters.Two games in one for double the fun. Simple, straightforward controls, new playable characters optimized for younger and less-experienced players, and a wealth of bonus content, such as a Hints gallery and helpful reference videos**, make this a perfect choice for anyone looking to introduce their family to the wonderful world of Mario. All a player needs is one Joy-Con controller, so two people can team up right out of the box. Tackle 164 platforming courses in two main game modes, and enjoy extra replayability with three additional game modes, in which you can also play as a Mii character: Challenges, Boost Rush, and Coin Battle.",
      features: "Two Super Mario Bros. games in one for double the fun A variety of playable characters are available, some with unique attributes that affect gameplay and platforming physics. Younger and less-experienced players will love playing as Toadette, who is brand-new to both games, and Nabbit, who was formerly only playable in New Super Luigi U. Both characters offer extra assistance during play. Multiplayer sessions are even more fun, frantic, and exciting thanks to entertaining character interactions. Need a boost? Try jumping off a teammate's head or getting a teammate to throw you. Features a wealth of help features, such as a Hints gallery, reference videos**, and a Super Guide in New Super Mario Bros. U that can complete levels for you if they're giving you trouble. Three additional modes - Boost Rush, Challenges, and Coin Battle - mix up gameplay and add replayability while also upping the difficulty for players who want to try something harder. Players can use their Mii characters in these modes",
      included: "New Super Mario Bros. U Deluxe",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6311/1544712004_ap.jpg;maxHeight=112;maxWidth=200"],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1544712004&amp;mobile=true",
      video_length: ["0:59"],
      reviews_count: 26,
      reviews_breakdown: [7,10,6,1,2],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "Comic mischief", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Model Number"],
      general: ["New Super Mario Bros. U Deluxe", "Nintendo", "Nintendo", "Nintendo", "HACPADALA"],
      game_Details_title: ["Genre", "Game Franchise", "Game Series", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Action and Adventure, Platformer", "Super Mario Bros.", "U Deluxe", "Yes", "4", "No"],
      requirements_title: ["Subscription"],
      requirements: ["No"],
      other_title: ["UPC"],
      other: "045496592691",
      questions: 14,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/bundle-super-mario-deluxe.png",
      bundle_total : [69.99, 79.99, 59.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/bundle-super-mario-deluxe.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Mario+Deluxe/quest-super-mario-bundle.png"
    }, 
    {
      name: "Namco Museum Arcade Pac",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "84005",
      publisher: "BANDAI NAMCO Entertainment",
      sku: "6",
      product_sku: "6276403",
      release_date: "09/28/2018",
      esrb_rating: "T (Teen 13+)",
      price: 29.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/namco-1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/namco-2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/namco-3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/namco-4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/namco-5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/namco-6.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 5.99,
      description: "Share your nostalgia in Namco Museum Arcade Pac for Nintendo Switch. Classic games such as Pac-Man, Galaga and Splatterhouse provide old-school challenges, while Pac-Man Championship Edition 2 Plus offers a modern take on the old game. Namco Museum Arcade Pac features new multiplayer modes in games such as Tank Force, so you and your friends can remember the good times together.",
      features: "You get the ultimate two-in-one game pack, which includes Namco Museum and PAC-MAN Championship Edition 2 Plus. Namco Museum highlights: Enjoy Namco classics such as PAC-MAN, Galaga, Splatterhouse and The Tower Of Druaga, or play games such as Rolling Thunder, SkyKid, or Tank Force with friends and family on the Nintendo Switch. Featuring impressive high-resolution 3D graphics and funky visuals, the latest version of the classic game takes chomping and chasing through mazes to a whole new level",
      included: "Namco Museum Arcade Pac",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/5d269344f43ddbcaea6fa10aee1c59dc.jpg;maxHeight=112;maxWidth=200"],
      miniplayer_videos: "https://www.totaleclips.com/Bounce/b?eclipid=e161428&amp;bitrateid=472&amp;vendorid=302",
      video_length: ["0:48"],
      reviews_count: 35,
      reviews_breakdown: [3,8,9,11,4],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["T (Teen 13+)", "Blood and gore, Suggestive themes, Violence", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Recommended Minium Age", "Model Number"],
      general: ["Namco Museum Arcade Pac", "BANDAI NAMCO Entertainment", "BANDAI NAMCO Entertainment", "BANDAI NAMCO Entertainment", "13 years", "84005"],
      game_Details_title: ["Genre", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Arcade", "Yes", "1", "No"],
      requirements_title: ["Subscription"],
      requirements: ["No"],
      other_title: ["UPC"],
      other: "047796590475",
      questions: 1,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/general/cyp.placeholder_mariokart.png",
      bundle_total : [69.99, 19.99, 59.99],
      manufacturer_img: "",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Namco+Museum/quest.png"
    },
    {
      name: "The Legend of Zelda: Breath of the Wild",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPAAAAA",
      publisher: "Nintendo",
      sku: "7",
      product_sku: "5726403",
      release_date: "03/28/2017",
      esrb_rating: "E10+ (Everyone 10+)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/zelda-1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/zelda-2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/zelda-3.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Travel back to Hyrule with Link in Zelda: Breath of the Wild for the Nintendo Switch. Explore a variety of shrines, sail across rough waters and scavenge for food to defeat Ganondorf and save Zelda once and for all. Zelda: Breath of the Wild includes Wolf, who joins Link in his adventure and delivers enhanced gameplay for greater enjoyment.",
      features: "Discover a world as never before seen: by making your own path, choices, and consequences. Surprises hide around every corner: scavenge weapons, armor, plants, animals, and more.",
      included: "Nintendo The Legend of Zelda: Breath of the Wild",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/1552142814_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/1753675103_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/1615998304_ap.jpg;maxHeight=112;maxWidth=200" ],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1753675103&amp;mobile=true",
      video_length: ["0:30"],
      reviews_count: 21,
      reviews_breakdown: [3,6,1,5,6],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E10+ (Everyone 10+)", "Fantasy violence, Mild suggestive themes, Use of alcohol", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Recommended Minium Age", "Model Number"],
      general: ["The Legend of Zelda: Breath of the Wild", "Nintendo", "Nintendo", "Nintendo", "10 years", "HACPAAAAA"],
      game_Details_title: ["Genre", "Game Franchise","Game Series", "Multiplayer","Maximum Number Of Players", "Starter Pack"],
      game_details: ["Action and Adventure", "The Legend of Zelda", "Breath of the Wild", "No", "1", "No"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["Nintendo Switch, software update","No"],
      other_title: ["UPC"],
      other: "047796590420",
      questions: 7,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/bundle.png",
      bundle_total : [19.99, 14.99, 19.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/manu.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/quest.png"
    }, 
    {
      name: "Luigi's Mansion 3",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPAA3JA",
      publisher: "Nintendo",
      sku: "8",
      product_sku: "6255379",
      release_date: "10/31/2019",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/1.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/2.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/3.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/4.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/5.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/6.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/7.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/8.png","https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/9.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Luigi's dream vacation turns into a ghostly - and gooey - nightmare. Luigi embarks on a dream vacation with Mario and friends upon receiving an invitation to a luxurious hotel. However, his dream quickly becomes a nightmare when King Boo reveals everything had been a ploy to capture Mario and friends. With the assistance of Professor E. Gadd once again, the reluctant and cowardly hero Luigi traverses up and down treacherous floors of the now-ominous hotel on a quest to save them. Wield the upgraded Poltergust G-00 to slam and blow away the ghosts' defenses, or summon Gooigi, an all-green doppelganger that can help Luigi overcome obstacles he can't get past alone. Interchange between Luigi and Gooigi as one player, or take a friend and control one each. For more frenetic multiplayer action, race the timer to clear various objectives on a series of floors in ScareScraper mode. ScareScraper mode can be played online* or locally with up to eight players on four Nintendo Switch systems (additional games required; sold separately).",
      features: "He may still be cowardly, but Luigi has more tools and abilities at his disposal than before",
      included: "Luigi's Mansion 3",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: [],
      miniplayer_videos: "",
      video_length: [],
      reviews_count: 27,
      reviews_breakdown: [4,2,4,10,7],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "Comic mischief, Mild cartoon violence", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Model Number"],
      general: ["Luigi's Mansion 3", "Nintendo", "Nintendo", "Next Level Games", "HACPAA3JA"],
      game_Details_title: ["Genre", "Multiplayer","Maximum Number Of Players"],
      game_details: ["Action and Adventure", "Yes", "8"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["Nintendo Switch, software update","No"],
      other_title: ["UPC"],
      other: "045496596408",
      questions: 12,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/bundle.png",
      bundle_total : [9.99, 74.99, 19.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Luigi+Mansion+3/manu.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/questions/twelve.png"
    }, 
    {
      name: "The Legend of Zelda: Link's Awakening",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPAA3NA",
      publisher: "Nintendo",
      sku: "9",
      product_sku: "5726362",
      release_date: "03/28/2019",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/3.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/4.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/5.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/6.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/7.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/8.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/9.png","https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/10.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Link has washed ashore on a mysterious island with strange and colorful inhabitants. To escape the island, Link must collect magical instruments across the land and awaken the Wind Fish. Explore a reimagined Koholint Island that's been faithfully rebuilt in a brand-new art style that will entice fans and newcomers alike. Battle enemies as you conquer numerous dungeons and uncover the hidden secrets of the island. Encounter Super Mario enemies, such as Goombas, Piranha Plants and more, and interact with unique locals who help Link on his adventure. As you clear dungeons throughout the main story, earn Dungeon Rooms (Chambers), then arrange them into custom layouts in the all-new Chamber Dungeon. Place your dungeon entrance, nightmare room, and everything in between as you try to fulfill objectives and play through a new dungeon. Tap compatible amiibo™ figures to earn more Chambers and find additional Chambers throughout the game in updated mini-games, such as the river rapids, trendy game, and fishing.",
      features: "As Link, explore a reimagined Koholint Island, and collect instruments to awaken the Wind Fish to find a way home. Explore numerous dungeons riddled with tricks, traps, and enemies, including some from the Super Mario™ series",
      included: "Nintendo The Legend of Zelda: Breath of the Wild",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6255/1307290708_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6255/1796172645_ap.jpg;maxHeight=112;maxWidth=200" ],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1796172645&amp;mobile=true",
      video_length: ["0:59"],
      reviews_count: 28,
      reviews_breakdown: [4,9,3,6,6],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "Mild fantasy violence", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Model Number"],
      general: ["The Legend of Zelda: Link's Awakening", "Nintendo", "Nintendo", "Nintendo",  "HACPAA3NA"],
      game_Details_title: ["Genre", "Game Franchise","Game Series", "Multiplayer","Maximum Number Of Players"],
      game_details: ["Action and Adventure", "The Legend of Zelda", "Link's Awakening", "No", "1"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["Nintendo Switch, software update","No"],
      other_title: ["UPC"],
      other: "047796590545",
      questions: 7,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/bundle.png",
      bundle_total : [19.99, 49.99, 59.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Link+Awakening/manu.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/quest.png"
    }, 
    {
      name: "Donkey Kong Country: Tropical Freeze",
      category: "Nintendo Switch",
      sub_category: "Nintendo Switch Games",
      model: "HACPAAWTA",
      publisher: "Nintendo",
      sku: "10",
      product_sku: "5726416",
      release_date: "05/28/2018",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/1.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/2.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/3.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/4.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/5.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/6.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/7.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/8.png","https://bb-clone.s3-us-west-1.amazonaws.com/Donkey+Kong+Tropical/9.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch-compatible-icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii-compatible-icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Take on new challenges with the old Kong crew when you play Donkey Kong Country Tropical Freeze for Nintendo Switch. Donkey, Diddy, Dixie and Cranky team up for more jumps and rolls, while Funky Kong climbs onto his trusty surfboard to show off his best moves. Rated E for everyone, Donkey Kong Country Tropical Freeze is an ideal option for family game night.",
      features: "Explore new dynamic levels that twist, turn, and transform in new ways. Enjoy spectacular views from the dynamic rotating camera. Unlock hidden collectibles and take down powerful bosses as you swim, swing, and jump through six islands full of puzzles and enemies",
      included: "Donkey Kong Country: Tropical Freeze",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/1552142814_ap.jpg;maxHeight=112;maxWidth=200" ],
      miniplayer_videos: "https://sc.liveclicker.net/service/qr?1753675103&amp;mobile=true",
      video_length: ["0:30"],
      reviews_count: 34,
      reviews_breakdown: [4,5,8,6,11],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "Cartoon violence", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Model Number"],
      general: ["Donkey Kong Country: Tropical Freeze", "Nintendo", "Nintendo", "Retro Studios", "HACPAAWTA"],
      game_Details_title: ["Genre", "Multiplayer"],
      game_details: ["Platformer",  "Yes"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["Nintendo Switch, software update","No"],
      other_title: ["UPC"],
      other: "047796590660",
      questions: 7,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/bundle_super_smash-bros.png",
      bundle_total : [29.99, 24.99, 49.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/manu.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/quest.png"
    }, 
    {
      name: "DOOM Eternal Standard Edition",
      category: "PlayStation 4",
      sub_category: "PlayStation 4 Games",
      model: "DO5CSTP4PENA",
      publisher: "Bethesda",
      sku: "11",
      product_sku: "5725526",
      release_date: "03/28/2020",
      esrb_rating: "M (Mature 17+)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/1.png","https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/2.png","https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/6.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/platform_ps4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/platform_xbox.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Developed by id Software, DOOM® Eternal™ is the direct sequel to DOOM®, winner of The Game Awards' Best Action Game of 2016. Experience the ultimate combination of speed and power as you rip-and-tear your way across dimensions with the next leap in push-forward, first-person combat. Powered by idTech 7 and set to an all-new pulse-pounding soundtrack composed by Mick Gordon, DOOM Eternal puts you in control of the unstoppable DOOM Slayer as you blow apart new and classic demons with powerful weapons in unbelievable and never-before-seen worlds.As the DOOM Slayer, you return to find Earth has suffered a demonic invasion. Raze Hell and discover the Slayer's origins and his enduring mission to rip and tear…until it is done.",
      features: "Gain access to the latest demon-killing tech with the DOOM Slayer's advanced Praetor Suit, including a shoulder-mounted flamethrower and the retractable wrist-mounted DOOM Blade.",
      included: "DOOM Eternal",
      header_titles: ["Best Buy", "Video Games", "PlayStation 4", "PS4 Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/bf89f983458448a9752aae44d398c824.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/19a640fc47eef1a1889f1a748a6c0996.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/83726647c2c4cad38038c28be374fb78.jpg;maxHeight=112;maxWidth=200" ],
      miniplayer_videos: "https://www.totaleclips.com/Bounce/b?eclipid=e166403&amp;bitrateid=472&amp;vendorid=302",
      video_length: ["1:35"],
      reviews_count: 22,
      reviews_breakdown: [7,5,4,6,0],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs: ["M (Mature 17+)", "Blood and gore, Intense violence", "PlayStation 4", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Model Number"],
      general: ["DOOM Eternal Standard Edition", "Bethesda", "Bethesda", "id Software", "DO5CSTP4PENA"],
      game_Details_title: ["Genre", "Multiplayer"],
      game_details: ["First Person Shooter",  "Yes"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["PlayStation 4","No"],
      other_title: ["UPC"],
      other: "093155174139",
      questions: 7,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Doom+Eternal/bundle.png",
      bundle_total : [64.99, 24.99, 49.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/manu.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Zelda+breath+of+wild/quest.png"
    }
]

