module.exports = [
    {
      name: "Mario Kart 8 Deluxe",
      category: "Nintendo Switch",
      sub_category: "Nintendo Swtich Games",
      model: "HACPAABPA",
      publisher: "Nintendo",
      sku: "1",
      product_sku: "5723304",
      release_date: "04/28/2017",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/Mario+Kart+8+Deluxe+-+Nintendo+Switch-7.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch_icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii_icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Battle new enemies on a host of fun tracks with Mario Kart 8 Deluxe for the Nintendo Switch. Three new vehicles and a smart steering feature make this game perfect for both beginners or seasoned pros. In Mario Kart 8 Deluxe you can hold up to two items at a time to attack your enemies.",
      features: "Race your friends in the definitive version of Mario Kart 8, only on Nintendo Switch!\n Race as every character on every track from the Wii U version, including DLC characters and tracks \n Pop some balloons in the revamped Battle mode, complete with Balloon Battle and Bob-omb Blast \n Battle on new courses, like Urchin Underpass and Battle Stadium, or returning ones, such as GCN Luigi\"s Mansion and SNES Battle Course 1 \n Inkling Girl & Inkling Boy from Splatoon, King Boo, Dry Bones, and Bowser Jr. join the roster! \n Choose a new Smart Steering feature which makes driving and staying on the track easy even at 200cc \n Three new vehicles have been added, two are even inspired by Splatoon \n Carry two items at the same time \n Returning items include Boo, the item stealing ghost, and the Feather, which gives you a high jump in battle mode \n Drive through in 1080p HD quality in TV mode \n For 1 player or up to 12 players online multiplayer* \n * Nintendo Switch Online membership (sold separately) and Nintendo Account required for online play. Not available in all countries. Internet access required for online features. Terms apply. nintendo.com/switch-online",
      included: "Mario Kart 8 Deluxe",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/20e8f7ed4abe4ce59da5126768578888.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1799536929_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1044944662_ap.jpg;maxHeight=112;maxWidth=200"],
      miniplayer_videos: ["https://sc.liveclicker.net/service/qr?1858858501&amp;mobile=true", "https://sc.liveclicker.net/service/qr?1799536929&amp;mobile=true", "https://sc.liveclicker.net/service/qr?1044944662&amp;mobile=true"],
      video_length: ["5:02", "1.32"],
      reviews_count: 34,
      reviews_breakdown: [8,7,7,10,2],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E (Everyone)", "Comic mischief", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Developer", "Recommended Minium Age", "Model Number"],
      general: ["Mario Kart 8 Deluxe", "Nintendo", "Nintendo", "Nintendo", "0 years", "HACPAABPA"],
      game_Details_title: ["Genre", "Game Franchise", "Game Series", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Racing", "Mario Kart", "8", "Yes", "12", "No"],
      requirements_title: ["System Requirements", "Subscription", "Download Requirements"],
      requirements: ["Nintendo Switch, Nintendo Switch Online membership, Nintendo Account", "No", "Nintendo Account"],
      other_title: ["UPC"],
      other: "045496590475",
      questions: 27,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/general/cyp.placeholder_mariokart.png",
      bundle_total : [69.99, 19.99, 59.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Mario+Kart+8+Deluxe+-+Nintendo+Switch/images/manu_mario+kart+8+deluxe.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/general/questions_placeholder.png"
    },
    { 
      name: "Pokémon Sword Edition",
      category: "Nintendo Switch",
      sub_category: "Nintendo Swtich Games",
      model: "HACPALZAA",
      publisher: "Nintendo",
      sku: "2",
      product_sku: "6255366",
      release_date: "11/15/2019",
      esrb_rating: "E (Everyone)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_7.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_8.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_9.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/Pokemon_sword_edition_10.png"],
      compatible_platforms : ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch_icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii_icon.png"],
      geek_squad_price: 7.99,
      description: "A new generation of Pokémon is coming to the Nintendo Switch system. Become a Pokémon Trainer, and embark on a journey in the new Galar region. Choose from one of three new partner Pokémon: Grookey, Scorbunny, or Sobble. In this all-new adventure, you'll encounter new and familiar Pokémon as you catch, battle, and trade Pokémon while exploring new areas. Get ready for the next Pokémon adventure in the Pokémon Sword and Pokémon Shield games.",
      features : "Unlike others found in the Galar region, this Meowth can Gigantamax to take on an imposing, elongated appearance capable of using a mighty G-Max Move! \n As you trek across this diverse region, you'll encounter wild Pokémon to catch and rival Trainers eager to battle. Choose one of three new partner Pokémon, strategically form a Pokémon team, bond with them throughout your journey, and face the odds together. \n Explore a whole new region full of never-before-seen Pokémon. \n Embark on a new Pokémon journey as a Pokémon Trainer. Catch, battle, and trade Pokémon on an all-new adventure in the Galar region",
      included: "Pokémon Sword Edition",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/exc/videometadata/thumbnail/d921a1a964bc841698d01cde4f15f720.jpg;maxHeight=112;maxWidth=200"],
      miniplayer_videos: ["https://sc.liveclicker.net/service/qr?1643758036&amp;mobile=true" ],
      video_length: ["2:13"],
      reviews_count: "28" ,
      reviews_breakdown: [3,6,4,9,6], 
      keyspecs_title: ["Edition", "ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["Sword Edition", "E (Everyone)", "Comic mischief, Mild cartoon violence", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher", "Model Number"],
      general: ["Pokémon Sword Edition", "Nintendo", "Nintendo", "HACPAABPA"],
      game_Details_title: ["Edition", "Genre", "Game Franchise", "Game Series"],
      game_details: ["Sword Edition", "Role Playing", "Pokemon", "Sword and Shield"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements:["Nintendo Switch", "No"],
      other_title: ["UPC"],
      other: "045496590475",
      questions: 9,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/bundle_pokemon_sword_edition.png",
      bundle_total : [29.99, 19.99, 49.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/manu_pokemon_sword_edition.png",
      questions_img:"https://bb-clone.s3-us-west-1.amazonaws.com/Pokemon+Sword+Edition/questions_pokemon_sword_edition.png"
    },
    {
      name: "Super Smash Bros. Ultimate",
      category: "Nintendo Switch",
      sub_category: "Nintendo Swtich Games",
      model: "HACPAAABA",
      publisher: "Nintendo",
      sku: "3",
      product_sku: "5723319",
      release_date: "12/07/2018",
      esrb_rating: "E10+ (Everyone 10+)",
      price: 59.99,
      images: ["https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_1.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_2.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_3.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_4.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_5.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_6.png", "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/super_smash_bros_7.png"],
      compatible_platforms: ["https://bb-clone.s3-us-west-1.amazonaws.com/general/switch_icon.png", "https://bb-clone.s3-us-west-1.amazonaws.com/general/wii_icon.png"],
      software_format: ["Physical", "Digital"],
      geek_squad_price: 7.99,
      description: "Choose your character in Super Smash Bros. for Nintendo Switch. Its expanded roster and new levels let you brawl it out with your friends with your favorite characters in iconic locations from Nintendo games. Super Smash Bros. has both local and online multiplayer, so you can play with your friends wherever you go.",
      features: "New fighters, new stages, and every fighter ever featured in the series",
      included: "Super Smash Bros. Ultimate",
      header_titles: ["Best Buy", "Video Games", "Nintendo Switch", "Nintendo Switch Games"],
      still_img_videos: ["https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1297102016_ap.jpg;maxHeight=112;maxWidth=200", "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5723/1514902275_ap.jpg;maxHeight=112;maxWidth=200" ],
      miniplayer_videos: ["https://sc.liveclicker.net/service/qr?1297102016&amp;mobile=true", "https://sc.liveclicker.net/service/qr?1514902275&amp;mobile=true"],
      video_length: ["0:57", "1:00"],
      reviews_count: 20,
      reviews_breakdown: [2,4,5,4,5],
      keyspecs_title: ["ESRB Rating", "ESRB Descriptors", "Compatible Platform(s)", "Software Format"],
      keyspecs : ["E10+ (Everyone 10+)", "Cartoon violence, Comic mischief, Mild suggestive themes", "Nintendo Switch", "Physical"],
      general_title: ["Product Name", "Brand", "Publisher","Recommended Minium Age", "Model Number"],
      general: ["Super Smash Bros. Ultimate", "Nintendo", "10 years", "HACPAABPA"],
      game_Details_title: ["Genre", "Game Franchise", "Game Series", "Multiplayer", "Maximum Number Of Players", "Starter Pack"],
      game_details: ["Fighting", "Super Smash Bros.", "Ultimate", "Yes", "8", "No"],
      requirements_title: ["System Requirements", "Subscription"],
      requirements: ["Nintendo Switch", "No"],
      other_title: ["UPC"],
      other: "045496592998",
      questions: 54,
      bundle: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/bundle_super_smash-bros.png",
      bundle_total : [29.99, 24.99, 49.99],
      manufacturer_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/manu_super_smash_bros.png",
      questions_img: "https://bb-clone.s3-us-west-1.amazonaws.com/Super+Smash+Bros/questions_super_smash-bros.png"
    }
    
]
